### PR TITLE
Greek Terminology

### PR DESCRIPTION
**Pull request by oeAdgK01**
This is the first version of the Greek Terminology.

### CODE REVIEW

**Comment by erciccione** [comment]
Hey @oeAdgK01 Thank you. We can leave this PR here for some time in case some Greek speaker have suggestions/comments.

Are these terms already used consistently in our translated content?

**Comment by oeAdgK01** [comment]
@erciccione Sure. We are checking the consistency for the translated content now.

**Comment by oeAdgK01** [comment]
> Are these terms already used consistently in our translated content?

@erciccione The translated content (GUI Wallet and the Getmonero website) are now up to date with the Greek terminology of this PR.

**Comment by erciccione** [comment]
@oeAdgK01 Thanks for the upddate. I'll merge this soon.

**Comment by erciccione** [comment]
Note that glossaries on this repository are not that important anymore. Weblate has drastically improved its native support, so now the glossaries gets populated automatically. Merging this PR anyway.

**Pull request merged**
