### PR TITLE
Update of german-terminology.md (including changes from #46)

### PR DESCRIPTION
**Pull request by erciccione**
This is #45 recovered, with added the use of `Das wallet` and `Das node`. This guide should be synced with m2049r/xmrwallet#556 as well.

### CODE REVIEW

**Comment by erciccione** [comment]
Edited. Thanks @Leza89

**Comment by Leza89** [comment]
I guess you misunderstood me. We are using "Node" as-is but the article is "der Node" because the literal translation would be "der (Netzwerk-)Knoten"

**Comment by erciccione** [comment]
Got it, changed to `Der node`. Thanks for the review.

> similar to "das Wallet", this was rejected by most other translators in that thread.

Come on... on #46 we have 4 people for `Das` and 4 + 1 non native speaker for `Die`. Most of the people vouching for `Die` said they care much about which version will be used. On reddit the comments were basically 50/50 (more people for `das` if you count upvotes). As I said, that's not a clear consensus and i'm not going to have a language split because **1 single contributor** can't accept to use a word instead of another one. I suggest you to think about the reason why you want to force the use of that word, maybe it's related to your past bad experiences as translator? (we spoke about it provately).

You contributed a lot to the localization workgroup and i have a good opinion of you, but you are acting in a very childish way. Just be honest with yourself and accept the situation.

**Comment by Leza89** [comment]
I disagree with your handling of the situation, your unwillingness to compromise on your position (different articles over different projects; I gave you the example of another project _insisting_ on using a different article later on) and your reason to favor "das"  because of gender neutrality which I and other translators [see #46] fundamentally disagree on. I won't have my usage of _my_ language dictated by others; especially not if the tendency goes in my preferred direction and there is no rational reason on why to change it. I will not use austrian language to determine my german language. I also don't know how you're counting the "votes" – I gave a list of the opinions by different groups and there is no 50/50 split: There is a clear favor for "die".

 I'd probably be hypocritical if this was in favor of my position and not critizise you as much as I'm doing now though.

If you think that this is childish of me, than this is your point of view and from your experience probably valid. I personally don't think though that having principles is childish.

**Comment by erciccione** [comment]
> I gave a list of the opinions by different groups in #46 and there is no 50/50 split: There is a clear favor for "die".

Then you definitely see something than is different from the truth, i cannot help you with that.

> 50% in favor of the other option

If you think that a 57% consensus (according to your wrong metrics) is a good reason to create a language split, i'm very happy that you are not the one coordinating this workgroup and just confirms that I made the right choice. If it doesn't sound absurd to you having two different languages because you (and only you, keep that in mind) refuse to use another word from the one you prefer, there is clearly no way that this is going to be a productive discussion.

> You have been dishonest about your motivation concerning gender neutrality. (You called it first in IRC and then denied it when a translator disagreed with your position in IRC; In #46 you reactivated this position again.)

This is you failing to understand (or pretending) that my intrervention on the matter was only caused by the absence of consensus and not justan arbitrary change. i won't waste more time on this particular point.
I never denied that i prefer that term because gender neutral, I understood this is the thing that triggered you for personal reasons (as you told me in private),  so i avoided to use the term again and just put it on a practical way: if i accepted your arrogance and use the word you wanted, we would have had a language split, if i go for the other choice, no language split and an arrogant contributor pissed off - i preferred this last choice.

> Overall it feels too centralized to me, which is probably the biggest issue I have in all of this.

Then you failed to understand that Monero workgroups are not decentralized entitities and they are not meant to be, because that wouldn't work, the drama you created only confirms it.

> Reflect on why you felt attacked by the whole community because @xeagu was not immediately dismissed.

I never felt attacked by the community, you (again) completely misunderstood the situation. i got upset on the gitlab issue because i think some community members fear the "censorship" label, and because of that give too much space to malicious people like Xeagu. This is something that i consider a "community attack", but i can assure you i never felt attacked by the community, but completely the opposite (the comments on that issue prove it).

Anyway, it's clear to me that this discussion won't lead anywere. You apparently see things in your own way and refuse to accept the situation.

This is my last comment on the matter.

**Comment by Leza89** [comment]
I'll just leave this here in case you decide to attack me later on.

>If you think that a 57% consensus (according to your wrong metrics) [...]

21st of March 2019; #monero-translations (IRC)

>21:40:39) ErCiccione[m]: I don't understand why you say there must be a way to change terminology. Of course there is, **if the translators agree on changing a term**, it gets changed. **It always worked that way**, i don't understand why became a question now.

from #46 

Translators:

    das: |||
    die: |||||| (67%)

das: Wobole, leonklingele, Rafficer
die: rodolfo912, ordtrogen, Leza89, lovvskillz, rbrunner7, (+ Keksoj)

I just put the _total_ numbers to show that even with your _wrong_ metrics you are _still_ in the minority.

>[...] to create a language split [...]

Using different articles is not a language split. A language split would be to use "Geldbörse" in the GUI and "Wallet" in Monerujo. It is your position to keep everything 100% homogenous and this is not even addressed as a possibility because the emperor ErCiccione decided so.

>This is you failing to understand (or pretending) that my intrervention on the matter was only caused by the absence of consensus and not justan arbitrary change.

No. I'm merely saying that you decided to use "das" because you favor "das". I never said that you initiated the change because of that. I'm just saying that you go against previously, by yourself, set terms on how to determine the used terminology.

>Then you failed to understand that Monero workgroups are not decentralized entitities and they are not meant to be, because that wouldn't work, the drama you created only confirms it.

If you think that you are the CEO of Monero translations, than maybe it is time to decentralize it more. Don't worry; You will not have to do anything for that.


>I never felt attacked by the community, you (again) completely misunderstood the situation.

from https://repo.getmonero.org/monero-project/ccs-proposals/merge_requests/53:

>The ONE commenter against my proposal has shown to not understand how the the workgroup i cordinate works. After all the work i do and keep doing, far beyond the amount of hours i'm paid for, i must say i'm very disappointed by the fact that a single rogue member who, as you all know, i called out for his scammy behaviour multiple times (maybe this is the reason he is questioning my proposal?) has the power to delay my CCS, especially when 6 other people already gave their support.

**Pull request merged**
