### PR TITLE
Es terminology

### PR DESCRIPTION
**Pull request by lh1008**
Hello everyone,

Adding new comments and words to the Spanish terminology. Everything new, like always, should be tried out through the community and see how it goes. 

The word "pruning" when literally translated means, "clean", "reduce", or "eliminate". If we translate the word exactly it might give meaning but not a clear concept of what pruning means in software development. Anyway, I'll leave it here so anyone can check it out.

Thank you.

Pinging @erciccione

### CODE REVIEW

**Comment by erciccione** [comment]
If we don't get comments on this in the next days, i'll just merge

**Comment by arawako** [comment]
Greetings friends, @lh1008 it is true what you say about all those meanings of the word "prune" in the context to which that word refers, it can be translated as clean (limpiar) or reduce (reducir), for example: A blockchain that you want to optimize the most appropriate would be to reduce or clean it to low the size by pruning unnecessary things.
In this context, we refer to the word prune.

**Comment by lh1008** [comment]
Yes @arawako. I'm not sure if I understand your comment. So you approve the word translations for "pruning" or "prune" could be, "limpieza" or "reducir"?
While translating the site you also used the word "reducir" for pruning and I did accepted it because it does mean what is trying to be said in the conext of using the "pruned blockchain".

**Comment by anhdres** [comment]
Regarding pruning I like the kinda literal translation "podar" which I think visually describes the idea of cutting out everything that is not vital to make it leaner and lighter. It should be clarified in context, probably, but once done it should make it stronger as a term.

"Reducido" or "limpio" introduces many conceptual errors IMO. "Podado" may be a cleaner, non charged term.

**Comment by lh1008** [comment]
@anhdres, I don't know, "podar" it's a very real world nature definition, "podar" -> cut the grass, branches, trees. Looking at some other definitions in the software development world found these: simplify, compress, optimize, remove, eliminate. 
Just to give a closer concept, pruning in software terminology is removing data, some say for a decision tree, so the word "podar" does give a meaning of what prune does but like I said, I think, in my opinion, that it's a more nature approach instead of a mire digital approach. What do you think?

**Comment by anhdres** [comment]
I tend to like when real world very visual terms eventually trickle into abstract usage, and not the other way around. I think technically savvy users make that usage jump faster than novice users do, adopting technical jargon and appropriating it.

My second choice would be "limpia", but again I think it introduces a level of ambiguity that is too high (specially since we're on an environment of private txs, tainted or not tainted coins, etc).

Maybe... a good compromise would be "recortada" which implies some cutting but leaving a relevant portion still on. I don't know if I'm using a too-local definition, but that's another word I would personally use if I'm explaining a pruned blockchain to someone: _"...una cadena recortada, donde se eliminan los excesos y se conserva la información crítica."_

**Comment by lh1008** [comment]
I prefer "recortada" than "podada". Let me add it.

**Comment by erciccione** [comment]
See https://github.com/monero-ecosystem/monero-translations/pull/95#issuecomment-813977242

**Comment by lh1008** [comment]
Understood @erciccione, so this means we no longer need to maintain or build the terminology? What does it mean weblate has improved its native support?

**Pull request closed without merging**
