### PR TITLE
add opening/closing sentences translations as per PR #70

### PR DESCRIPTION
**Pull request by netrik182**
ping @intj440

### CODE REVIEW

**Comment by erciccione** [comment]
Any update on this?

**Comment by intj440** [comment]
@erciccione Is my understanding correct that Weblate requires that the *.srt subtitle files across all languages to have identical timestamp structures, _i.e._, the same # of subtitles & the same timing for each subtitle?

If so, then in the latest English .srt file from #70, a few "milestone subtitles" are as follows:  
- sub 16 = part 1
- sub 443 = part 2
- sub 768 = part 3
- sub 1088 = part 4
- sub 1234 = the "want to get started?" slide that begins the end credits
- sub 1287 = final sub

Presently, some of these mismatch with the BR-PT subtitle structure in PR #71.

**Comment by netrik182** [comment]
yeah, somehow it mismatches. I'll update this file to match the english version. Thanks for reviewing @intj440

**Comment by erciccione** [comment]
Ping @netrik182

**Comment by netrik182** [comment]
> Ping @netrik182

pong @erciccione :wink: 

Thank you for your patience. I was very busy during the last couple of weeks.

**Comment by erciccione** [comment]
Don't worry, it was just a friendly ping in case you forgot :)

Merging.

**Pull request merged**
