### PR TITLE
Add terminology guide for Turkish

### PR DESCRIPTION
**Pull request by erciccione**
This glossary was created by Nine-zero  - English-Turkish translations for blockchain and cryptocurrency projects, i ported it to a markdown and adapted to the style of the other glossaries.

The team of Nine-zero [recently translated the website in Turkish](https://repo.getmonero.org/monero-project/monero-site/merge_requests/1055#note_5775) (not merged yet).

### CODE REVIEW

**Comment by erciccione** [comment]
@xmoreee maybe you want to take a look at this

**Comment by erciccione** [comment]
@xmoreee Please make your comments in English, i don't speak Turkis :).

**Comment by xmoreee** [comment]
> @xmoreee Thanks for your review, but please make your comments in English, i don't speak Turkish :P (in any case, comments here should always be in english for clarity of the readers)

:)
OK, fixed the top comment but discussions about individual words/phrases kept in Turkish.
E.g. it is already hard to assign a proper term for "fungible" in Turkish. It would be real pain if we discuss it English.

**Comment by erciccione** [comment]
Thank you for editing. Btw, i didn't mean to translate the actual term in english, but the discussion. For example:

`"Fungible" kelimesini çevirmek zor.[...]`

Would be better: `It's hard to translate the word "Fungible."[..]`, so that I and other members of the localization workgroup can understand what the discussion is about. For example, see the discussion happeing in #9 about Spanish terminology . Not a big deal tho, no worries :).

**Comment by erciccione** [comment]
Reguarding your suggestions, the terms suggested here are the ones used in https://repo.getmonero.org/monero-project/monero-site/merge_requests/1055, so if one is changed on the terminology guide, it should be changed there as well, for consistency. Could you discuss this with translators on the issue on gitlab?

**Comment by erciccione** [comment]
Closing this. Glossaries are now automatically populated on Weblate (see https://github.com/monero-ecosystem/monero-translations/pull/95#issuecomment-813977242)

**Pull request closed without merging**
